import type { Metadata } from "next";
import { Inter } from 'next/font/google';
import { ClerkProvider } from '@clerk/nextjs';
import Navbar from "@/components/navbar/navbar";
import "./globals.css";
import { ThemeProvider } from "@/components/theme-provider"
import { shadcn } from '@clerk/themes';
import { Toaster } from 'react-hot-toast';



const inter = Inter({ 
  subsets: ['latin'],
  variable: '--font-inter', // اختياري: إذا أردت استخدام CSS variable
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  

  return (
    <ClerkProvider
      appearance={{
        baseTheme: shadcn
      }}
    >
      <html lang="en" suppressHydrationWarning >
        <body
          className={`${inter.variable} `}
        >
          <ThemeProvider
            attribute="class"
            defaultTheme="dark"
            enableSystem
            disableTransitionOnChange
          >
            <div className="relative">

            <Navbar />
              <Toaster
                position="top-center"
                toastOptions={{
                  duration: 5000,
                  style: {
                    background: '#363636',
                    color: '#fff',
                  },
                  error: {
                    duration: 8000,
                  },
                }}
              />
              {children}
            </div>
          </ThemeProvider>
        </body>
      </html>
    </ClerkProvider >

  );
}
